application: test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/\1
  upload: dist/(.*\.html)
  expiration: "1h"
  
 # site root
- url: /
  static_files: dist/select.html
  upload: dist/select.html
  expiration: "15m"