application: test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/\1
  upload: dist/(.*\.html)
  expiration: "1h"
  
 # site root
- url: /.*
  script: main.app
  
librairies: 
- name: pytorch 
  version: latest